stages: 
  run_experiment:
    cmd: python main.py --params params.yaml
                        --model_outpath models/${EXPERIMENT_NAME}.pt
                        --experiment_name ${EXPERIMENT_NAME}
                        --run_name ${RUN_NAME}_3
    deps:
      - params.yaml
      - main.py