dataset:
  train_batch_size: 256
  val_batch_size: 512
  test_batch_size: 1000
  train_transforms:
    _target_: src.collections.augmentations.torch_transforms.get_train_transforms
  test_transforms:
    _target_: src.collections.augmentations.torch_transforms.get_val_transforms
  train_augm: null
  test_augm: null
  val_size: 0.15
  download: false
  random_state: 42
  num_workers: 32
model:
  net:
    _target_: src.collections.models.resnet.ResNet50
    _partial_: false
transforms:
  train:
    _target_: src.collections.augmentations.torch_transforms.get_train_transforms
  val:
    _target_: src.collections.augmentations.torch_transforms.get_val_transforms
criterion:
  criterion:
    _target_: torch.nn.CrossEntropyLoss
optimizer:
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0002
    weight_decay: 0.01
metrics:
  accuracy_score:
    _target_: sklearn.metrics.accuracy_score
    _partial_: true
  recall_score:
    _target_: sklearn.metrics.recall_score
    _partial_: true
    average: weighted
  precision_score:
    _target_: sklearn.metrics.precision_score
    _partial_: true
    average: weighted
trainer:
  trainer_kwargs:
    accelerator: cuda
    devices: 1
    min_epochs: 2000
    max_epochs: 2001
    check_val_every_n_epoch: 1
    enable_model_summary: true
    gradient_clip_val: null
    gradient_clip_algorithm: null
DEVICE: cuda
DEVICE_NUM: 1
GPU_NUM: 1
EXPERIMENT_NAME: GrokkingEffect
RUN_NAME: ResNet50_no_augm_4
DESCRIPTION: null
CKPT_PATH: null
