dataset:
  train_batch_size: 128
  val_batch_size: 256
  test_batch_size: 500
  train_transforms:
    _target_: src.collections.augmentations.torch_transforms.get_resize_to_tensor
  test_transforms:
    _target_: src.collections.augmentations.torch_transforms.get_resize_to_tensor
  train_augm: null
  test_augm: null
  val_size: 0.15
  download: false
  random_state: 42
  num_workers: 32
model:
  net:
    _target_: src.collections.models.vit.VisionTransformer
    _partial_: false
    embed_dim: 256
    hidden_dim: 512
    num_heads: 8
    num_layers: 6
    patch_size: 4
    num_channels: 3
    num_patches: 64
    num_classes: 10
    dropout: 0.2
transforms:
  train:
    _target_: src.collections.augmentations.torch_transforms.get_resize_to_tensor
  val:
    _target_: src.collections.augmentations.torch_transforms.get_resize_to_tensor
criterion:
  criterion:
    _target_: torch.nn.CrossEntropyLoss
optimizer:
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.0002
scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    min_lr: 1.0e-05
    verbose: false
metrics:
  accuracy_score:
    _target_: sklearn.metrics.accuracy_score
    _partial_: true
  recall_score:
    _target_: sklearn.metrics.recall_score
    _partial_: true
    average: weighted
  precision_score:
    _target_: sklearn.metrics.precision_score
    _partial_: true
    average: weighted
trainer:
  trainer_kwargs:
    accelerator: cpu
    devices: 1
    min_epochs: 1000
    max_epochs: 1100
    check_val_every_n_epoch: 1
    enable_model_summary: true
DEVICE: cpu
DEVICE_NUM: 0
GPU_NUM: 1
EXPERIMENT_NAME: GrokkingEffect
RUN_NAME: ResNet50_no_augm
CKPT_PATH: null
