train:
  _target_: src.dataset.ClassificationDataset
  _partial_: True
  transform: ${augmentation.train}
val: 
  _target_: src.dataset.ClassificationDataset
  _partial_: True
  transform: ${augmentation.val}
