Compose:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomResizedCrop
      size: 32
      scale: 
        - 0.25
        - 1 

    - _target_: torchvision.transforms.ToTensor
  
    - _target_: torchvision.transforms.RandomApply
      transforms:
        - _target_: src.collections.augmentations.classification.GaussianNoise
          mean: 0
          std: 0.1
      p: 1
    - _target_: torchvision.transforms.ToPILImage