net:
  _target_: src.collections.models.vit.VisionTransformer
  _partial_: False
  embed_dim: 1
  hidden_dim: 1
  num_channels: 1
  num_heads: 1
  num_layers: 1
  num_classes: 1
  patch_size: 1
  num_patches: 1
  dropout: 1