# https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#trainer-class-api
# Очень много возможностей для настройки (буквально всё что только можно)
# Рекомендуется подробно изучить и взять всё что необходимо для ваших задач.

trainer_kwargs:
  default_root_dir: ${EXPERIMENT_NAME}/${RUN_NAME}
  accelerator: ${DEVICE}
  devices: ${GPU_NUM}
  min_epochs: 2000
  max_epochs: 2001
  check_val_every_n_epoch: 1
  enable_model_summary: True
  gradient_clip_val: null
  gradient_clip_algorithm: null  