# https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#trainer-class-api
# Очень много возможностей для настройки (буквально всё что только можно)
# Рекомендуется подробно изучить и взять всё что необходимо для ваших задач.

trainer_kwargs:
  accelerator: ${DEVICE}
  devices: ${GPU_NUM}
  min_epochs: 1000
  max_epochs: 1100
  check_val_every_n_epoch: 1
  enable_model_summary: True
  # gradient_clip_val: 0.5
  # gradient_clip_algorithm: value